package pg_classify

import (
	"testing"

	"apercu-cli/helper/pg_catalog"
	"apercu-cli/helper/pg_contract"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

const (
	ael  = pg_contract.LockAccessExclusive
	sre  = pg_contract.LockShareRowExclusive
	sue  = pg_contract.LockShareUpdateExclusive
	rs   = pg_contract.LockRowShare
	sh   = pg_contract.LockShare
	meta = pg_contract.OpKindMetadata
	scan = pg_contract.OpKindScan
	rw   = pg_contract.OpKindRewrite
)

func TestColumnSubcommands(t *testing.T) {
	t.Parallel()

	cases := []ruleCase{
		// R-AT-ADDCOL
		{name: "a plain column is a catalog entry", sql: "ALTER TABLE orders ADD COLUMN note text", code: "R-AT-ADDCOL", lock: ael, op: meta},
		{name: "a constant default is still a catalog entry", sql: "ALTER TABLE orders ADD COLUMN n int DEFAULT 7", code: "R-AT-ADDCOL", lock: ael, op: meta},
		{name: "a stable default is not a volatile one", sql: "ALTER TABLE orders ADD COLUMN at timestamptz DEFAULT now()", code: "R-AT-ADDCOL", lock: ael, op: meta},
		{name: "a volatile default writes every row", sql: "ALTER TABLE orders ADD COLUMN c text DEFAULT next_code()", code: "R-AT-ADDCOL", lock: ael, op: rw},
		{name: "a stored generated column is materialised", sql: "ALTER TABLE orders ADD COLUMN d int GENERATED ALWAYS AS (id * 2) STORED", code: "R-AT-ADDCOL", lock: ael, op: rw},
		{name: "an identity column draws a value per row", sql: "ALTER TABLE orders ADD COLUMN k int GENERATED BY DEFAULT AS IDENTITY", code: "R-AT-ADDCOL", lock: ael, op: rw},
		{name: "a constrained domain is checked against every row", sql: "ALTER TABLE orders ADD COLUMN s positive_int", code: "R-AT-ADDCOL", lock: ael, op: rw},
		{name: "an unconstrained domain is not", sql: "ALTER TABLE orders ADD COLUMN s loose_text", code: "R-AT-ADDCOL", lock: ael, op: meta},
		{name: "an inline unique constraint builds an index", sql: "ALTER TABLE orders ADD COLUMN u text UNIQUE", code: "R-AT-ADDCOL", lock: ael, op: scan},

		// R-AT-DROPCOL.
		{name: "dropping a column is catalog only", sql: "ALTER TABLE orders DROP COLUMN status", code: "R-AT-DROPCOL", lock: ael, op: meta},

		// R-AT-TYPE
		{name: "a USING expression recomputes every row", sql: "ALTER TABLE orders ALTER COLUMN status TYPE text USING upper(status)", code: "R-AT-TYPE", lock: ael, op: rw},
		{name: "a USING that only names the column is not a transform", sql: "ALTER TABLE orders ALTER COLUMN status TYPE text USING status", code: "R-AT-TYPE", lock: ael, op: meta},
		{name: "a relaxed numeric modifier keeps the bytes", sql: "ALTER TABLE orders ALTER COLUMN total TYPE numeric(12,2)", code: "R-AT-TYPE", lock: ael, op: meta},
		{name: "a moved numeric scale does not", sql: "ALTER TABLE orders ALTER COLUMN total TYPE numeric(10,4)", code: "R-AT-TYPE", lock: ael, op: rw},
		{name: "text to a bounded varchar rewrites", sql: "ALTER TABLE users ALTER COLUMN email TYPE varchar(20)", code: "R-AT-TYPE", lock: ael, op: rw, table: "apercu_snapshot_test.users"},
		{name: "dropping an unconstrained domain is a relabel", sql: "ALTER TABLE profiles ALTER COLUMN note TYPE text", code: "R-AT-TYPE", lock: ael, op: meta, table: "apercu_snapshot_test.profiles"},
		{name: "a narrower integer rewrites", sql: "ALTER TABLE orders ALTER COLUMN id TYPE int", code: "R-AT-TYPE", lock: ael, op: rw},

		// R-AT-SETDEF / R-AT-DROPDEF.
		{name: "setting a default touches no row", sql: "ALTER TABLE orders ALTER COLUMN status SET DEFAULT 'open'", code: "R-AT-SETDEF", lock: ael, op: meta},
		{name: "dropping a default touches no row", sql: "ALTER TABLE orders ALTER COLUMN status DROP DEFAULT", code: "R-AT-DROPDEF", lock: ael, op: meta},

		// R-AT-SETNOTNULL / R-AT-DROPNOTNULL.
		{name: "a validated CHECK already proves NOT NULL", sql: "ALTER TABLE orders ALTER COLUMN status SET NOT NULL", code: "R-AT-SETNOTNULL", lock: ael, op: meta},
		{name: "nothing proving it means a full scan", sql: "ALTER TABLE orders ALTER COLUMN code SET NOT NULL", code: "R-AT-SETNOTNULL", lock: ael, op: scan},
		{name: "dropping NOT NULL proves nothing and reads nothing", sql: "ALTER TABLE orders ALTER COLUMN status DROP NOT NULL", code: "R-AT-DROPNOTNULL", lock: ael, op: meta},

		// R-AT-ADDIDENT / R-AT-SETIDENT / R-AT-DROPIDENT.
		{name: "attaching identity keeps the values", sql: "ALTER TABLE orders ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY", code: "R-AT-ADDIDENT", lock: ael, op: meta},
		{name: "changing identity options is catalog only", sql: "ALTER TABLE orders ALTER COLUMN id RESTART WITH 100", code: "R-AT-SETIDENT", lock: ael, op: meta},
		{name: "dropping identity keeps the values", sql: "ALTER TABLE orders ALTER COLUMN id DROP IDENTITY", code: "R-AT-DROPIDENT", lock: ael, op: meta},

		// R-AT-SETSTATS / R-AT-ATTROPT.
		{name: "a statistics target needs no more than a vacuum's lock", sql: "ALTER TABLE orders ALTER COLUMN status SET STATISTICS 500", code: "R-AT-SETSTATS", lock: sue, op: meta},
		{name: "an attribute option needs no more than a vacuum's lock", sql: "ALTER TABLE orders ALTER COLUMN status SET (n_distinct = 10)", code: "R-AT-ATTROPT", lock: sue, op: meta},
		{name: "resetting one is the same clause", sql: "ALTER TABLE orders ALTER COLUMN status RESET (n_distinct)", code: "R-AT-ATTROPT", lock: sue, op: meta},

		// R-AT-SETSTORAGE / R-AT-SETCOMPRESSION.
		{name: "storage changes later writes", sql: "ALTER TABLE orders ALTER COLUMN status SET STORAGE EXTERNAL", code: "R-AT-SETSTORAGE", lock: ael, op: meta},
		{name: "compression changes later writes", sql: "ALTER TABLE orders ALTER COLUMN status SET COMPRESSION lz4", code: "R-AT-SETCOMPRESSION", lock: ael, op: meta},

		// R-AT-RENAMECOL.
		{name: "renaming a column is catalog only", sql: "ALTER TABLE orders RENAME COLUMN status TO state", code: "R-AT-RENAMECOL", lock: ael, op: meta},
	}

	catalog := testCatalog(t)
	for _, testCase := range cases {
		t.Run(testCase.name, func(t *testing.T) { testCase.run(t, catalog) })
	}
}

func TestAlterColumnTypeRebuildsItsIndexes(t *testing.T) {
	t.Parallel()

	analysis := single(t, testCatalog(t), "ALTER TABLE labels ALTER COLUMN name TYPE varchar(10)")
	finding := findingOf(t, analysis, "R-AT-TYPE")

	index := targetOf(t, finding, "apercu_snapshot_test.labels_name_idx")
	assert.Equal(t, pg_contract.OpKindRewrite, index.OpKind)
	assert.Equal(t, pg_contract.TargetRoleResolved, index.Role)
}

func TestTimestampTypeChangeFollowsTimeZone(t *testing.T) {
	t.Parallel()

	cases := []struct {
		name   string
		script string
		op     pg_contract.OpKind
	}{
		{
			name:   "under UTC the conversion is the identity",
			script: "ALTER TABLE users ALTER COLUMN created_at TYPE timestamp",
			op:     pg_contract.OpKindMetadata,
		},
		{
			name:   "under any other zone every value shifts",
			script: "SET TimeZone = 'Europe/Paris'; ALTER TABLE users ALTER COLUMN created_at TYPE timestamp",
			op:     pg_contract.OpKindRewrite,
		},
		{
			name:   "a SET LOCAL outside a block does not change the zone",
			script: "SET LOCAL TimeZone = 'Europe/Paris'; ALTER TABLE users ALTER COLUMN created_at TYPE timestamp",
			op:     pg_contract.OpKindMetadata,
		},
	}

	for _, testCase := range cases {
		t.Run(testCase.name, func(t *testing.T) {
			analyses := analyze(t, testCatalog(t), testCase.script)
			last := analyses[len(analyses)-1]
			finding := findingOf(t, last, "R-AT-TYPE")
			assert.Equal(t, testCase.op.String(), targetOf(t, finding, "apercu_snapshot_test.users").OpKind.String())
		})
	}
}

// TestDefaultVolatilityWalksTheParsedTree test the expression walker for default volatility detection.
func TestDefaultVolatilityWalksTheParsedTree(t *testing.T) {
	t.Parallel()

	cases := []struct {
		name string
		sql  string
		op   pg_contract.OpKind
	}{
		{
			name: "a string literal that reads like a call is a string literal",
			sql:  "ALTER TABLE orders ADD COLUMN c text DEFAULT 'next_code()'",
			op:   pg_contract.OpKindMetadata,
		},
		{
			name: "a volatile function nested in an expression is still volatile",
			sql:  "ALTER TABLE orders ADD COLUMN c text DEFAULT ('x' || next_code())",
			op:   pg_contract.OpKindRewrite,
		},
		{
			name: "a volatile function behind a cast is still volatile",
			sql:  "ALTER TABLE orders ADD COLUMN c text DEFAULT next_code()::text",
			op:   pg_contract.OpKindRewrite,
		},
		{
			name: "a volatile function inside a CASE is still volatile",
			sql:  "ALTER TABLE orders ADD COLUMN c text DEFAULT (CASE WHEN true THEN next_code() ELSE 'x' END)",
			op:   pg_contract.OpKindRewrite,
		},
		{
			name: "a function nothing in the snapshot explains is treated as volatile",
			sql:  "ALTER TABLE orders ADD COLUMN c text DEFAULT no_such_function()",
			op:   pg_contract.OpKindRewrite,
		},
		{
			name: "a subquery reads a relation the snapshot cannot grade",
			sql:  "ALTER TABLE orders ADD COLUMN c text DEFAULT (SELECT max(status) FROM orders)",
			op:   pg_contract.OpKindRewrite,
		},
	}

	catalog := testCatalog(t)
	for _, testCase := range cases {
		t.Run(testCase.name, func(t *testing.T) {
			finding := findingOf(t, single(t, catalog, testCase.sql), "R-AT-ADDCOL")
			assert.Equal(t, testCase.op.String(), targetOf(t, finding, "apercu_snapshot_test.orders").OpKind.String())
		})
	}
}

// TestGeneratedColumnClauses test R-AT-SETEXPR and R-AT-DROPEXPR.
func TestGeneratedColumnClauses(t *testing.T) {
	t.Parallel()

	catalog := testCatalogOn(t, pg_contract.Version18)

	t.Run("a stored expression is recomputed for every row", func(t *testing.T) {
		finding := findingOf(t, single(t, catalog, "ALTER TABLE computed ALTER COLUMN stored_total SET EXPRESSION AS (1)"), "R-AT-SETEXPR")
		assert.Equal(t, pg_contract.OpKindRewrite, targetOf(t, finding, "apercu_snapshot_test.computed").OpKind)
	})

	t.Run("a virtual expression stores nothing to recompute", func(t *testing.T) {
		finding := findingOf(t, single(t, catalog, "ALTER TABLE computed ALTER COLUMN virtual_total SET EXPRESSION AS (1)"), "R-AT-SETEXPR")
		assert.Equal(t, pg_contract.OpKindMetadata, targetOf(t, finding, "apercu_snapshot_test.computed").OpKind)
	})

	t.Run("dropping a stored expression keeps the values", func(t *testing.T) {
		finding := findingOf(t, single(t, catalog, "ALTER TABLE computed ALTER COLUMN stored_total DROP EXPRESSION"), "R-AT-DROPEXPR")
		assert.Equal(t, pg_contract.OpKindMetadata, targetOf(t, finding, "apercu_snapshot_test.computed").OpKind)
	})

	t.Run("a virtual column has no expression to drop", func(t *testing.T) {
		analysis := single(t, catalog, "ALTER TABLE computed ALTER COLUMN virtual_total DROP EXPRESSION")
		assert.Empty(t, analysis.Findings)
		require.Len(t, analysis.Errors, 1)
		assert.Contains(t, analysis.Errors[0].Message, "virtual generated columns")
	})
}

func TestDropColumnCarriesItsViews(t *testing.T) {
	t.Parallel()

	finding := findingOf(t, single(t, testCatalog(t), "ALTER TABLE users DROP COLUMN email"), "R-AT-DROPCOL")
	view := targetOf(t, finding, "apercu_snapshot_test.active_users")
	assert.Equal(t, pg_contract.LockAccessExclusive, view.Lock)
	assert.Equal(t, pg_contract.TargetRoleImplicit, view.Role)
}

// overloadCatalog is a synthetic pair of snapshots holding one ambiguous function name: two
// overloads that take no argument and disagree on volatility, so the name alone cannot settle it.
func overloadCatalog(t *testing.T, resolvedTo pg_catalog.OID) *pg_catalog.Catalog {
	t.Helper()

	relations := []pg_catalog.Relation{{OID: 1, Namespace: "public", Name: "t", Kind: "r", AccessMethod: "heap"}}
	pre := &pg_catalog.Snapshot{
		Source:    pg_catalog.SourcePreview,
		PIT:       pg_catalog.PITPre,
		Header:    pg_catalog.Header{Version: pg_contract.Version17, User: "postgres", SearchPath: "public"},
		Relations: relations,
		Procs: []pg_catalog.Proc{
			{OID: 100, Namespace: "public", Name: "pick", Volatility: "i", Kind: "f"},
			{OID: 101, Namespace: "public", Name: "pick", Volatility: "v", Kind: "f"},
		},
		Settings: []pg_catalog.Setting{{Name: "search_path", Value: "public"}},
	}

	options := pg_catalog.CatalogOptions{Pre: pre}
	if resolvedTo != 0 {
		options.Post = &pg_catalog.Snapshot{
			Source:    pg_catalog.SourcePreview,
			PIT:       pg_catalog.PITPost,
			Header:    pre.Header,
			Relations: relations,
			Columns:   []pg_catalog.Column{{RelID: 1, Num: 1, Name: "c", FormattedType: "text"}},
			Defaults:  []pg_catalog.ColumnDefault{{RelID: 1, Num: 1, Expr: "pick()", ReferencedProcs: []pg_catalog.OID{resolvedTo}}},
		}
	}
	catalog, err := pg_catalog.NewCatalog(options)
	require.NoError(t, err)
	return catalog
}

// TestVolatilityLadderAsksThePostSnapshot test that when the name and the argument count leave two overloads standing,
// the dependency the post-migration snapshot recorded names the one the server actually picked.
func TestVolatilityLadderAsksThePostSnapshot(t *testing.T) {
	t.Parallel()

	cases := []struct {
		name       string
		resolvedTo pg_catalog.OID
		op         pg_contract.OpKind
	}{
		{name: "the immutable overload costs nothing", resolvedTo: 100, op: pg_contract.OpKindMetadata},
		{name: "the volatile one costs a rewrite", resolvedTo: 101, op: pg_contract.OpKindRewrite},
		{name: "with nothing to ask, the worst overload stands", resolvedTo: 0, op: pg_contract.OpKindRewrite},
	}

	for _, testCase := range cases {
		t.Run(testCase.name, func(t *testing.T) {
			catalog := overloadCatalog(t, testCase.resolvedTo)
			finding := findingOf(t, single(t, catalog, "ALTER TABLE t ADD COLUMN c text DEFAULT pick()"), "R-AT-ADDCOL")
			assert.Equal(t, testCase.op.String(), targetOf(t, finding, "public.t").OpKind.String())
		})
	}
}
