package pg_parse

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"go.yaml.in/yaml/v3"
)

const (
	corpusPath = "testdata/corpus.yaml"
	goldenPath = "testdata/corpus.golden.yaml"

	// goldenHeader is prepended to the golden because YAML carries no other place to say it.
	goldenHeader = "# Generated by TestCorpusMatchesGolden. Do not edit by hand: regenerate with `make golden` and review the diff.\n"
)

// corpusEntry is one entry of the corpus: the rule id §4 or §5 gives the shape, and a statement
// that exercises it.
type corpusEntry struct {
	Rule string `yaml:"rule"`
	SQL  string `yaml:"sql"`
}

func loadCorpus(t *testing.T) []corpusEntry {
	t.Helper()

	raw, err := os.ReadFile(corpusPath)
	require.NoError(t, err)

	var entries []corpusEntry
	require.NoError(t, yaml.Unmarshal(raw, &entries))
	require.NotEmpty(t, entries)

	seen := make(map[string]bool, len(entries))
	for i, entry := range entries {
		require.NotEmptyf(t, entry.Rule, "%s: entry %d has no rule", corpusPath, i)
		require.NotEmptyf(t, entry.SQL, "%s: %s has no sql", corpusPath, entry.Rule)
		require.Falsef(t, seen[entry.Rule], "%s: %s appears twice", corpusPath, entry.Rule)
		seen[entry.Rule] = true
	}
	return entries
}

// TestCorpusMatchesGolden normalize every entries in corpus.yaml and check that it's output match the corpus.golden.yaml
func TestCorpusMatchesGolden(t *testing.T) {
	entries := loadCorpus(t)

	fixtures := make([]fixtureStatement, 0, len(entries))
	for _, entry := range entries {
		statements := Parse(entry.SQL)
		require.Lenf(t, statements, 1, "%s: expected one statement", entry.Rule)
		fixtures = append(fixtures, newFixture(entry.Rule, statements[0]))
	}
	rendered := goldenHeader + marshalFixtures(t, fixtures)

	if os.Getenv("APERCU_UPDATE_FIXTURES") != "" {
		require.NoError(t, os.MkdirAll(filepath.Dir(goldenPath), 0o755))
		require.NoError(t, os.WriteFile(goldenPath, []byte(rendered), 0o644))
		t.Log("golden regenerated")
		return
	}

	want, err := os.ReadFile(goldenPath)
	require.NoError(t, err, "run with 'make golden' to create the golden")
	assert.Equal(t, string(want), rendered)
}

// TestCorpusParses validate that nothing in the corpus fall back to the unparseable path.
func TestCorpusParses(t *testing.T) {
	t.Parallel()

	for _, entry := range loadCorpus(t) {
		t.Run(entry.Rule, func(t *testing.T) {
			t.Parallel()

			statements := Parse(entry.SQL)
			require.Len(t, statements, 1)
			statement := statements[0]

			assert.Truef(t, statement.Parsed(), "did not parse: %s", statement.Unparsed)
			assert.NotEmpty(t, statement.Command)
			assert.Equal(t, entry.SQL, statement.RawSQL)
			for _, feature := range statement.Features {
				assert.Truef(t, feature.Since.IsSupported(),
					"feature %q has no supported minimum version", feature.Name)
			}
		})
	}
}

// The corpus fixture type
type fixtureStatement struct {
	Rule        string            `yaml:"rule"`
	SQL         string            `yaml:"sql"`
	Command     string            `yaml:"command"`
	Unparsed    string            `yaml:"unparsed,omitempty"`
	Flags       []string          `yaml:"flags,omitempty,flow"`
	Options     []string          `yaml:"options,omitempty,flow"`
	Features    []fixtureFeature  `yaml:"features,omitempty"`
	Relations   []fixtureRelation `yaml:"relations,omitempty"`
	Subcommands []fixtureSub      `yaml:"subcommands,omitempty"`
}

type fixtureFeature struct {
	Name      string `yaml:"name"`
	Since     string `yaml:"since"`
	Detail    string `yaml:"detail,omitempty"`
	Ambiguous bool   `yaml:"ambiguous,omitempty"`
}

type fixtureRelation struct {
	Schema string `yaml:"schema,omitempty"`
	Table  string `yaml:"table"`
	Kind   string `yaml:"kind,omitempty"`
	Only   bool   `yaml:"only,omitempty"`
	Alias  string `yaml:"alias,omitempty"`
}

type fixtureSub struct {
	Kind       string             `yaml:"kind"`
	Name       string             `yaml:"name,omitempty"`
	NewName    string             `yaml:"new_name,omitempty"`
	Value      string             `yaml:"value,omitempty"`
	Flags      []string           `yaml:"flags,omitempty,flow"`
	Options    []string           `yaml:"options,omitempty,flow"`
	Expr       string             `yaml:"expr,omitempty"`
	Relations  []fixtureRelation  `yaml:"relations,omitempty"`
	Column     *fixtureColumn     `yaml:"column,omitempty"`
	Constraint *fixtureConstraint `yaml:"constraint,omitempty"`
}

type fixtureColumn struct {
	Name          string              `yaml:"name"`
	Type          string              `yaml:"type,omitempty"`
	Generated     string              `yaml:"generated,omitempty"`
	GeneratedExpr string              `yaml:"generated_expr,omitempty"`
	Default       string              `yaml:"default,omitempty"`
	Using         string              `yaml:"using,omitempty"`
	Collation     []string            `yaml:"collation,omitempty,flow"`
	Constraints   []fixtureConstraint `yaml:"constraints,omitempty"`
}

type fixtureConstraint struct {
	Type              string           `yaml:"type"`
	Name              string           `yaml:"name,omitempty"`
	Columns           []string         `yaml:"columns,omitempty,flow"`
	KeyExprs          []string         `yaml:"key_exprs,omitempty,flow"`
	Expr              string           `yaml:"expr,omitempty"`
	References        *fixtureRelation `yaml:"references,omitempty"`
	ReferencedColumns []string         `yaml:"referenced_columns,omitempty,flow"`
	UsingIndex        string           `yaml:"using_index,omitempty"`
	Tablespace        string           `yaml:"tablespace,omitempty"`
	Options           []string         `yaml:"options,omitempty,flow"`
	NotValid          bool             `yaml:"not_valid,omitempty"`
	NotEnforced       bool             `yaml:"not_enforced,omitempty"`
	EnforcementSet    bool             `yaml:"enforcement_set,omitempty"`
	NoInherit         bool             `yaml:"no_inherit,omitempty"`
	Inherit           bool             `yaml:"inherit,omitempty"`
	NoInheritSet      bool             `yaml:"inherit_set,omitempty"`
	Deferrable        bool             `yaml:"deferrable,omitempty"`
	InitiallyDef      bool             `yaml:"initially_deferred,omitempty"`
	DeferralSet       bool             `yaml:"deferral_set,omitempty"`
	WithoutOverlaps   bool             `yaml:"without_overlaps,omitempty"`
	Period            bool             `yaml:"period,omitempty"`
}

// marshalFixtures indents two spaces rather than the library's four.
func marshalFixtures(t *testing.T, fixtures []fixtureStatement) string {
	t.Helper()

	var buffer bytes.Buffer
	encoder := yaml.NewEncoder(&buffer)
	encoder.SetIndent(2)
	require.NoError(t, encoder.Encode(fixtures))
	require.NoError(t, encoder.Close())
	return buffer.String()
}

func newFixture(rule string, s Statement) fixtureStatement {
	fixture := fixtureStatement{
		Rule:    rule,
		SQL:     s.RawSQL,
		Command: string(s.Command),
	}
	if s.Unparsed != "" {
		fixture.Unparsed = s.Unparsed
		return fixture
	}

	fixture.Flags = flagNames(s.Flags)
	fixture.Options = optionNames(s.Options)
	for _, feature := range s.Features {
		fixture.Features = append(fixture.Features, fixtureFeature{
			Name:      string(feature.Name),
			Since:     feature.Since.String(),
			Detail:    feature.Detail,
			Ambiguous: feature.Ambiguous,
		})
	}
	for _, rel := range s.Relations {
		fixture.Relations = append(fixture.Relations, newFixtureRelation(rel))
	}
	for _, sub := range s.Subcommands {
		fixture.Subcommands = append(fixture.Subcommands, newFixtureSub(sub))
	}
	return fixture
}

func newFixtureRelation(rel RelationRef) fixtureRelation {
	fixture := fixtureRelation{
		Schema: rel.Name.Schema,
		Table:  rel.Name.Table,
		Only:   rel.Only,
		Alias:  rel.Alias,
	}
	if rel.Kind != 0 {
		fixture.Kind = rel.Kind.String()
	}
	return fixture
}

func newFixtureSub(sub Subcommand) fixtureSub {
	fixture := fixtureSub{
		Kind:    sub.Kind.String(),
		Name:    sub.Name,
		NewName: sub.NewName,
		Value:   sub.Value,
		Flags:   flagNames(sub.Flags),
		Options: optionNames(sub.Options),
	}
	if sub.Expr != nil {
		fixture.Expr = sub.Expr.String()
	}
	for _, rel := range sub.Relations {
		fixture.Relations = append(fixture.Relations, newFixtureRelation(rel))
	}
	if sub.Column != nil {
		column := newFixtureColumn(*sub.Column)
		fixture.Column = &column
	}
	if sub.Constraint != nil {
		constraint := newFixtureConstraint(*sub.Constraint)
		fixture.Constraint = &constraint
	}
	return fixture
}

func newFixtureColumn(column ColumnDef) fixtureColumn {
	fixture := fixtureColumn{
		Name:      column.Name,
		Type:      column.Type.String(),
		Collation: column.Collation,
	}
	if column.Generated != GeneratedNone {
		fixture.Generated = column.Generated.String()
	}
	if column.GeneratedExpr != nil {
		fixture.GeneratedExpr = column.GeneratedExpr.String()
	}
	if column.Default != nil {
		fixture.Default = column.Default.String()
	}
	if column.Using != nil {
		fixture.Using = column.Using.String()
	}
	for _, constraint := range column.Constraints {
		fixture.Constraints = append(fixture.Constraints, newFixtureConstraint(constraint))
	}
	return fixture
}

func newFixtureConstraint(constraint ConstraintDef) fixtureConstraint {
	fixture := fixtureConstraint{
		Type:              constraint.Type.String(),
		Name:              constraint.Name,
		Columns:           constraint.Columns,
		ReferencedColumns: constraint.ReferencedColumns,
		UsingIndex:        constraint.UsingIndex,
		Tablespace:        constraint.Tablespace,
		Options:           optionNames(constraint.Options),
		NotValid:          constraint.NotValid,
		NotEnforced:       constraint.NotEnforced,
		EnforcementSet:    constraint.EnforcementSet,
		NoInherit:         constraint.NoInherit,
		Inherit:           constraint.Inherit,
		NoInheritSet:      constraint.NoInheritSet,
		Deferrable:        constraint.Deferrable,
		InitiallyDef:      constraint.InitiallyDef,
		DeferralSet:       constraint.DeferralSet,
		WithoutOverlaps:   constraint.WithoutOverlaps,
		Period:            constraint.Period,
	}
	for _, expr := range constraint.KeyExprs {
		fixture.KeyExprs = append(fixture.KeyExprs, expr.String())
	}
	if constraint.Expr != nil {
		fixture.Expr = constraint.Expr.String()
	}
	if constraint.References.Name.Table != "" {
		references := newFixtureRelation(constraint.References)
		fixture.References = &references
	}
	return fixture
}

func flagNames(flags Flags) []string {
	var set []string
	for _, flag := range []struct {
		name string
		on   bool
	}{
		{"if_exists", flags.IfExists},
		{"if_not_exists", flags.IfNotExists},
		{"concurrently", flags.Concurrently},
		{"cascade", flags.Cascade},
		{"or_replace", flags.OrReplace},
		{"unique", flags.Unique},
		{"finalize", flags.Finalize},
		{"nowait", flags.Nowait},
		{"with_data", flags.WithData},
		{"restart_identity", flags.RestartIdentity},
	} {
		if flag.on {
			set = append(set, flag.name)
		}
	}
	if flags.Persistence != PersistencePermanent {
		set = append(set, strings.ToLower(flags.Persistence.String()))
	}
	return set
}

func optionNames(list []Option) []string {
	if len(list) == 0 {
		return nil
	}
	names := make([]string, 0, len(list))
	for _, option := range list {
		name := option.Name
		if option.Namespace != "" {
			name = option.Namespace + "." + name
		}
		if option.Value != "" {
			name += "=" + option.Value
		}
		names = append(names, name)
	}
	return names
}
